# Generated by Django 6.0.7 on 2026-08-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
