# Generated by Django 6.0.7 on 2026-08-03 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='isolation_forest', max_length=50)),
                ('column', models.CharField(max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detections', to='datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('arima', 'ARIMA'), ('sarimax', 'SARIMAX'), ('prophet', 'Prophet'), ('holt_winters', 'Holt-Winters'), ('linear_regression', 'Linear Regression'), ('exp_smoothing', 'Exponential Smoothing')], max_length=30)),
                ('target_column', models.CharField(max_length=255)),
                ('date_column', models.CharField(blank=True, max_length=255)),
                ('horizon', models.IntegerField(default=30)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('historical_data', models.JSONField(blank=True, default=dict)),
                ('forecast_data', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_models', to='datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
